### ISSUE TITLE
网页端已登录但仍显示未登录

### ISSUE THREAD

**Issue by Jayce-Jackson** [sethyuan/logseq-plugin-weread-sync#16]
设备：MacBook Pro M1
系统：14.1.1 (23B81)
浏览器：Arc 14.1.1 (23B81)
如题，两边都设置好了，打开网页微信读书的时候再次点击插件提示“请先登录微信读书”，请问下是否有解决办法

**Comment by sethyuan** [comment]
打开网页微信读书后等待一下，等页面加载好了再点插件按钮看看。

**Comment by darrenzhangxiaoyu** [comment]
遇到同样的问题，已经登录的网页版微信读书，点击插件还是提示 “请先登录微信读书”

**Comment by sethyuan** [comment]
看看是不是梯子的原因，不要用梯子，等网页加载完成再点按钮看看。

**Comment by Jayce-Jackson** [comment]
> 看看是不是梯子的原因，不要用梯子，等网页加载完成再点按钮看看。

经测试不挂梯子也还是显示“请先登录微信读书”

**Comment by sethyuan** [comment]
等到头像转出来之后，页面加载的进度条走完之后再点按钮。
<img width="424" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/3410293/f5554749-517f-4b5b-b6e0-651bf4ed19f9">

我这边刚试过了是可以的。

**Comment by darrenzhangxiaoyu** [comment]
好的，多谢了 ---- 回复的原邮件 ----发件人Seth ***@***.***>发送日期2024年01月04日 08:46 ***@***.***> ***@***.***>***@***.***>主题Re: [sethyuan/logseq-plugin-weread-sync] 网页端已登录但仍显示未登录 (Issue #16)
等到头像转出来之后，页面加载的进度条走完之后再点按钮。
image.png (view on web)
我这边刚试过了是可以的。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sethyuan/logseq-plugin-weread-sync/issues/16#issuecomment-1876160975",
"url": "https://github.com/sethyuan/logseq-plugin-weread-sync/issues/16#issuecomment-1876160975",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by trusun** [comment]
没挂梯子, 也加载完毕了, 同样是一直提示未登录

**Comment by sethyuan** [comment]
用的啥浏览器？我用的Chrome没问题。

**Comment by trusun** [comment]
抱歉抱歉, 非常抱歉, 重装了一下扩展可以了, chrome

**Comment by Jayce-Jackson** [comment]
最终经我测试，发现问题所在：
扩展的「Logseq API 地址」这一栏中，我必须填写“http://127.0.0.1/12315”而不是“http://127.0.0.1:12315”才能正确连接同步，不知道是不是Mac的问题，几个浏览器都测试了一下必须这么填写。

最后再问下删除划线和笔记是无法同步给logseq的对吧？

**Comment by sethyuan** [comment]
@Jayce-Jackson 会不会是因为你的Logseq的HTTP API Server的端口也没有配置对导致的？

另外划线和笔记的删除也是会同步的，除非你已经在Logseq中有对划线或笔记的引用了。
